# Generated by Django 2.0.4 on 2018-04-30 13:45

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('raulchirinos', '0003_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
