# Generated by Django 2.0.4 on 2018-05-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raulchirinos', '0005_auto_20180430_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
