# Generated by Django 2.0.4 on 2018-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raulchirinos', '0007_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
